#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE SCHEMA raw;

    CREATE TABLE IF NOT EXISTS raw.ocorrencias (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ano_ocorrencia INT,
        mes_ocorrencia INT,
        uf VARCHAR(2),
        municipio VARCHAR(100),
        especie_arma VARCHAR(100),
        marca_arma VARCHAR(100),
        calibre_arma VARCHAR(50),
        tipo_ocorrencia VARCHAR(255),
        mais_1000_mil_hab VARCHAR(1),
        total INT,
        dt_carga TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS raw.portes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ano_emissao INT,
        mes_missao INT,
        uf VARCHAR(2),
        municipio VARCHAR(100),
        tipo  VARCHAR(50),
        status  VARCHAR(50),
        abrangencia  VARCHAR(50),
        especie_arma VARCHAR(100),
        marca_arma VARCHAR(100),
        calibre_arma VARCHAR(50),
        sexo  VARCHAR(1),
        total INT,
        dt_carga TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS raw.registros (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ano_emissao INT,
        mes_missao INT,
        uf VARCHAR(2),
        municipio VARCHAR(100),
        status_registro VARCHAR(50),
        especie_arma VARCHAR(50),
        marca_arma VARCHAR(100),
        calibre_arma VARCHAR(50),
        sexo VARCHAR(1),
        categoria VARCHAR(244),
        total INT,
        dt_carga TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

EOSQL
