#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE SCHEMA raw;
    CREATE SCHEMA refined;

    CREATE TABLE IF NOT EXISTS raw.ocorrencias (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ano_ocorrencia INT,
        mes_ocorrencia INT,
        uf VARCHAR(2),
        municipio VARCHAR(244),
        especie_arma VARCHAR(244),
        marca_arma VARCHAR(244),
        calibre_arma VARCHAR(50),
        tipo_ocorrencia VARCHAR(255),
        mais_1000_mil_hab INT,
        total INT,
        dt_carga TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE refined.dim_uf (
        id_uf BIGINT PRIMARY KEY,
        desc_uf VARCHAR,
        dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE refined.dim_municipio (
        id_municipio BIGINT PRIMARY KEY,
        desc_municipio VARCHAR,
        dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE refined.dim_ocorrencia (
        id_ocorrencia BIGINT PRIMARY KEY,
        desc_ocorrencia VARCHAR,
        dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE refined.dim_marca (
        id_marca BIGINT PRIMARY KEY,
        desc_marca VARCHAR,
        dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE refined.dim_arma (
        id_arma BIGINT PRIMARY KEY,
        desc_arma VARCHAR,
        dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE refined.dim_calibre (
        id_calibre BIGINT PRIMARY KEY,
        desc_calibre VARCHAR,
        dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE refined.fat_ocorrencias (
        id BIGINT PRIMARY KEY,
        ano_ocorrencia INT,
        mes_ocorrencia INT,
        id_uf VARCHAR,
        id_municipio VARCHAR,
        id_ocorrencia VARCHAR,
        id_marca VARCHAR,
        id_arma VARCHAR,
        id_calibre VARCHAR,
        mais_1000_mil_hab INT,
        total INT,
        dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

EOSQL
