#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE sinarm;

    \c sinarm;

    CREATE SCHEMA raw;
    CREATE SCHEMA refined;

    CREATE TABLE IF NOT EXISTS raw.ocorrencias (
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ANO_OCORRENCIA INT,
        MES_OCORRENCIA INT,
        UF VARCHAR(2),
        MUNICIPIO VARCHAR(244),
        ESPECIE_ARMA VARCHAR(244),
        MARCA_ARMA VARCHAR(244),
        CALIBRE_ARMA VARCHAR(50),
        TIPO_OCORRENCIA VARCHAR(255),
        MAIS_1000_MIL_HAB INT,
        TOTAL INT
    );

    CREATE TABLE refined.dim_uf (
        id_uf BIGINT PRIMARY KEY,
        desc_uf VARCHAR
    );

    CREATE TABLE refined.dim_municipio (
        id_municipio BIGINT PRIMARY KEY,
        desc_municipio VARCHAR
    );

    CREATE TABLE refined.dim_ocorrencia (
        id_ocorrencia BIGINT PRIMARY KEY,
        desc_ocorrencia VARCHAR
    );

    CREATE TABLE refined.dim_marca (
        id_marca BIGINT PRIMARY KEY,
        desc_marca VARCHAR
    );

    CREATE TABLE refined.dim_arma (
        id_arma BIGINT PRIMARY KEY,
        desc_arma VARCHAR
    );

    CREATE TABLE refined.dim_calibre (
        id_calibre BIGINT PRIMARY KEY,
        desc_calibre VARCHAR
    );

    CREATE TABLE refined.fat_ocorrencias (
        id BIGINT PRIMARY KEY,
        ano_ocorrencia INT,
        mes_ocorrencia INT,
        id_uf VARCHAR,
        id_municipio VARCHAR,
        id_ocorrencia VARCHAR,
        id_marca VARCHAR,
        id_arma VARCHAR,
        id_calibre VARCHAR,
        mais_1000_mil_hab INT,
        total INT
    );

EOSQL
