SELECT 
    {{ dbt_utils.generate_surrogate_key(['MUNICIPIO', 'TIPO_OCORRENCIA', 'TIPO_OCORRENCIA', 'MARCA_ARMA']) }} AS SK_OCORRENCIA
    ,ID_OCORRENCIA
    ,MUNICIPIO
    ,TIPO_OCORRENCIA
    ,CALIBRE_ARMA
    ,ESPECIE_ARMA
    ,MARCA_ARMA
    ,ANO_OCORRENCIA
    ,MES_OCORRENCIA
    ,TOTAL
    ,CASE
        WHEN MAIS_1000_MIL_HAB = 'S' THEN 1
        ELSE 0
    END AS MAIS_1000_MIL_HAB
    ,DT_CARGA
    ,CURRENT_TIMESTAMP AS DT_CARGA_STG
FROM {{source('raw','ocorrencias')}}
